version: "3"
services: 
    api:
        image: ghcr.io/damikun/unifiededge:main
        # build: 
        #     context: ./Src
        #     dockerfile: Dockerfile
        #     args: 
        #         - MAX_OLD_SPACE=16384

        ports: 
            - "5001:5001"
            - "443:443"
            - "3000-3050:3000-3050"

        environment:
            - ASPNETCORE_HTTPS_PORT=5001
            - ASPNETCORE_URLS=https://+:5001
            # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - MIN_PORT=3000
            - MAX_PORT=3050
        volumes:
            - ~/.aspnet/https:/https:ro
        networks:
            - edge-net

networks:
  edge-net: