version: "3"
services: 
    api:
        build: 
            context: ./Src
            dockerfile: Dockerfile
            args: 
                - MAX_OLD_SPACE=16384
        ports: 
            - "5001:5001"
            - "443:443"

        environment:
            - ASPNETCORE_HTTPS_PORT=5001
            - ASPNETCORE_URLS="https://localhost:5001"