version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.32
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-example

      
networks:
  jaeger-example: